_target_: src.pl_models.imbalanced_classifier_model.ImbalancedClassifierModel
freeze_features: False
ckpt_path: null
reference_regularization: null
regularization_type: null
reference_ckpt_path: null
dont_update_correct_extras: False
flood_level: null
