# See https://huggingface.co/transformers/main_classes/optimizer_schedules.html#transformers.get_linear_schedule_with_warmup
_target_: transformers.get_linear_schedule_with_warmup
num_warmup_steps: 0
num_training_steps: null
interval: step
