defaults:
    - tokenizer: auto_tokenizer.yaml

# Taken from https://github.com/p-lambda/wilds/blob/e95bba8408aff524b48b96a4e7648df72773ad60/examples/configs/datasets.py
_target_: src.pl_datamodules.utils.make_datamodule
group_datamodule_cls_name: WILDSDataModule
wrapper_type: null

# WILDSDatamodule settings
dataset_name: amazon

train_transform:
    transform_name: bert
    config:
        max_token_length: 512
eval_transform: 
    transform_name: bert
    config:
        max_token_length: 512
groupby_fields: ["user"]


flatten_input: False
data_dir: ${data_dir}  # data_dir is specified in config.yaml
batch_size: null
num_workers: 0
pin_memory: True
num_classes: 2

