_target_: src.pl_datamodules.utils.make_datamodule
group_datamodule_cls_name: CelebADataModule
wrapper_type: null

# class labels:
# 0 : TODO
# 1 : TODO
resolution: null
augment_data: False
target_name: "Blond_Hair"
confounder_names: ["Male"]
flatten_input: False
data_dir: ${data_dir}  # data_dir is specified in config.yaml
batch_size: null
num_workers: 0
pin_memory: True
train_sampler: null
#train_frac: 1.0
train_frac: 0.05
