_target_: src.pl_datamodules.utils.make_datamodule
group_datamodule_cls_name: ImbalancedCIFAR10DataModule
wrapper_type: null

# CIFAR10 class labels:
# 0 : airplane
# 1 : automobile
# 2 : bird
# 3 : cat
# 4 : deer
# 5 : dog
# 6 : frog
# 7 : horse
# 8 : ship
# 9 : truck
#
# CIFAR10 classes are balanced, with 5000 examples per class in the train set
# and 1000 examples per class in the test set
imb_type: exp
imb_factor: 100
data_augmentation: False


flatten_input: False
data_dir: ${data_dir}  # data_dir is specified in config.yaml
batch_size: 16
num_workers: 0
pin_memory: False
