_target_: src.pl_datamodules.imbalanced_datamodule.ImbalancedMoonsDataModule

# Entries must correspond to entries of desired_classes sorted in increasing order
num_undersample_per_train_class: null
num_oversample_per_train_class: null
num_undersample_per_test_class: null
num_oversample_per_test_class: null

flatten_input: False
data_dir: ${data_dir}  # data_dir is specified in config.yaml
batch_size: 16
num_workers: 0
pin_memory: False

