defaults:
    - tokenizer: auto_tokenizer.yaml

_target_: src.pl_datamodules.utils.make_datamodule
group_datamodule_cls_name: MNLIDataModule
wrapper_type: null

train_frac: 1.0
#train_frac: 0.05  # for quick runs

flatten_input: False
data_dir: ${data_dir}  # data_dir is specified in config.yaml
batch_size: null
num_workers: 0
pin_memory: True
