# TODO: THIS IS A REGRESSION DATASET WHICH IS NOT CURRENTLY COMPATIBLE
# Taken from https://github.com/p-lambda/wilds/blob/e95bba8408aff524b48b96a4e7648df72773ad60/examples/configs/datasets.py
_target_: src.pl_datamodules.utils.make_datamodule
group_datamodule_cls_name: WILDSDataModule
dataset_name: poverty
train_transform:
    transform_name: poverty_train
    config: null
eval_transform: null  # TODO: should we make this same as train transform for our purposes?

flatten_input: False
data_dir: ${data_dir}  # data_dir is specified in config.yaml
batch_size: null
num_workers: 0
pin_memory: True
