_target_: src.pl_datamodules.utils.make_datamodule
group_datamodule_cls_name: WaterbirdsDataModule
wrapper_type: null

# class labels:
# 0 : landbird
# 1 : waterbird
resolution: null
augment_data: False
flatten_input: False
data_dir: ${data_dir}  # data_dir is specified in config.yaml
batch_size: null
num_workers: 0
pin_memory: True
